AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation templates to deploy Grafana and InfluxDB containers on ECS cluster

Mappings:
  # Mapping to store the region to ECS optimized AMI mapping
  RegionECSOptimizedAMI:
    us-east-2:
      AMI: ami-008c5ba1857e0fdec
    us-east-1:
      AMI: ami-09edd32d9b0990d49


Parameters:
  ServerConfigBucketName:
    Description: >
      Name of S3 bucket containining server configuration files. Upload the files to these bucket before
      starting the deployment.
    Type: String
    Default: influxdb-grafana-config

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  SubnetName:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Identifier of the subnet where the Container Instance will be deployed.

  VpcName:
    Type: AWS::EC2::VPC::Id
    Description: VPC Identifier of the VPC where the Container Instance will be deployed.

  InstanceType:
    Description: ECS Container Instance Type
    Type: String
    Default: m5ad.4xlarge
    ConstraintDescription: >
      Must be a valid EC2 instance type. Also should be able to support the Grafana and InfluxDB container CPU/Memory
      requirements, or else the stack deployment will get stuck and will never complete as the ECS service will keep
      searching for availability of a suitable Container Instance which satisfies the minimum requirements.

  AccessLocation:
    Description: The IP address range that can be used to access the Grafana and InfluxDB endpoints.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref AWS::StackName

  ECSInstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable access to ECS Container Instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref AccessLocation
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: !Ref AccessLocation
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: !Ref AccessLocation

  ECSContainerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  ECSContainerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref ECSContainerInstanceRole

  ECSContainerInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref ECSInstanceSecurityGroup
      IamInstanceProfile:  !Ref ECSContainerInstanceProfile
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionECSOptimizedAMI, !Ref 'AWS::Region', AMI]
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash
            echo 'INIT: update server'
            yum -y update
            sudo yum -y install awscli

            echo 'INIT: config to connect instance to cluster'
            sudo touch /etc/ecs/ecs.config
            sudo chmod 777 /etc/ecs/ecs.config
            sudo echo "ECS_CLUSTER=${AWS::StackName}" > /etc/ecs/ecs.config

            echo 'INIT: get the server config files from S3'
            sudo mkdir /data
            sudo chmod 777 /data
            cd /data
            aws s3 sync s3://${ServerConfigBucketName} .

            echo 'INIT: create data drive for InfluxDB data mount'
            sudo mkdir /data/influxdbdata

            echo 'INIT: update the ECS container agent, and restart'
            docker pull amazon/amazon-ecs-agent:latest
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            sudo docker run --name ecs-agent --detach=true --restart=on-failure:10 --volume=/var/run:/var/run --volume=/var/log/ecs/:/log --volume=/var/lib/ecs/data:/data --volume=/etc/ecs:/etc/ecs --net=host --env-file=/etc/ecs/ecs.config amazon/amazon-ecs-agent:latest

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref AWS::StackName
      Volumes:
        # Contains all dashboard .json files
        - Host:
            SourcePath: '/data/grafana/dashboards'
          Name: 'grafana-dashboards'
        # Grafana server custom configuration file
        - Host:
            SourcePath: '/data/grafana/custom.ini'
          Name: 'grafana-config'
        # Grafana dashboard provisioning
        - Host:
            SourcePath: '/data/provisioning'
          Name: 'grafana-provisioning'
        # InfluxDB data drive
        - Host:
            SourcePath: '/data/influxdbdata'
          Name: 'influxdb-data'

      ContainerDefinitions:
        - Name: grafana
          Image: grafana/grafana:6.3.4  # for latest version, use 'grafana/grafana'
          # Map to host port on which traffic is allowed using the Security Group
          PortMappings:
            - ContainerPort: 3000
              HostPort: 443
          HealthCheck:
            Command: [ "CMD-SHELL", "curl -G http://localhost:3000/api/health || exit 1" ]
            Interval: 10
          Cpu: 1024
          Memory: 2048
          MountPoints:
            - SourceVolume: 'grafana-dashboards'
              ContainerPath: '/var/lib/grafana/dashboards'
            - SourceVolume: 'grafana-config'
              ContainerPath: '/etc/grafana/custom.ini'
            - SourceVolume: 'grafana-provisioning'
              ContainerPath: '/etc/grafana/provisioning'
          Environment:
            # Env Vars for custom Grafana configuration
            - Name: 'GF_SECURITY_ADMIN_USER'
              Value: 'amol'
            - Name: 'GF_SECURITY_ADMIN_PASSWORD'
              Value: 'amol'
            - Name: 'GF_INSTALL_PLUGINS'
              Value: 'grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource'
            # Env Vars which are used by provisioning to configure the InfluxDB data source on Grafana
            # Ensure the creds here are the same as what are set for InfluxDB container
            - Name: 'INFLUXDB_USER'
              Value: 'amol'
            - Name: 'INFLUXDB_PASSWORD'
              Value: 'amol'
            - Name: 'INFLUXDB_DATA_PORT'
              Value: '8086'
            - Name: 'INFLUXDB_URL'
              Value: !Sub
                       - http://${InstancePrivateIP}:80
                       - { InstancePrivateIP: !GetAtt ECSContainerInstance.PrivateIp }
            # This is to add the data source for this database by default on start up
            - Name: 'INFLUXDB_DB'
              Value: 'Atop_Uploads'

        - Name: influxdb
          Image: influxdb:1.7.7  # for latest version, use 'influxdb'
          # Map to host port on which traffic is allowed using the Security Group
          PortMappings:
            - ContainerPort: 8086
              HostPort: 80
          HealthCheck:
            Command: [ "CMD-SHELL", "curl -G http://localhost:8086/ping || exit 1" ]
            Interval: 10
          Cpu: 4096
          Memory: 4096
          MountPoints:
            - SourceVolume: 'influxdb-data'
              ContainerPath: '/var/lib/influxdb"'
          Environment:
            - Name: 'INFLUXDB_ADMIN_USER'
              Value: 'amol'
            - Name: 'INFLUXDB_ADMIN_PASSWORD'
              Value: 'amol'
            - Name: 'INFLUXDB_DATA_ENGINE'
              Value: 'tsm1'
            - Name: 'INFLUXDB_REPORTING_DISABLED'
              Value: 'false'
            # This database is created by default on start up
            - Name: 'INFLUXDB_DB'
              Value: 'Atop_Uploads'


  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSTaskDefinition
      - ECSContainerInstance
    Properties:
      ServiceName: !Ref AWS::StackName
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: EC2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
